name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs daily at midnight PDT (7 AM UTC)
    - cron: '0 7 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "False" 
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LANGUAGE: "True"
          SHOW_SHORT_INFO: "False"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_LOC_CHART: "False"
          SHOW_PROFILE_VIEWS: "False"
        continue-on-error: true
      
      - name: Handle WakaTime API timeout
        if: failure()
        run: |
          echo "⚠️ WakaTime workflow failed, likely due to GitHub API timeout"
          echo "This is a known issue with the GitHub GraphQL API and will be retried on next run"
          echo "The failure does not affect repository functionality"
          
